iruby-notebook:
  build: .
  ports:
    - 8888:8888
  volumes:
    - ./notebooks:/notebooks
datascience-cv-notebook:
  image: izumin5210/datascience-cv-notebook
  ports:
    - 8888:8888
  volumes:
    - ./notebooks:/notebooks
tensorflow:
  image: gcr.io/tensorflow/tensorflow
  ports:
    - 8888:8888
  volumes:
    - ./notebooks:/notebooks
